fixtures:
  symlinks:
    profile: "#{File.dirname(source_dir)}/confcollect"
  forge_modules:
    accounts: 'puppetlabs/accounts'
    git: 'puppetlabs/git'
    epel: 'stahnma/epel'
    logrotate: 'puppet/logrotate'
    python: 'puppet-python'
    stdlib: 'puppetlabs/stdlib'
    vcsrepo: 'puppetlabs/vcsrepo'
