fixtures:
  symlinks:
    profile: "#{File.dirname(source_dir)}/confcollect"
  forge_modules:
    accounts: 'puppetlabs/accounts'
    cron_core: 'puppetlabs/cron_core'
    epel: 'puppet/epel'
    git: 'puppetlabs/git'
    logrotate: 'puppet/logrotate'
    python: 'puppet/python'
    stdlib: 'puppetlabs/stdlib'
    vcsrepo: 'puppetlabs/vcsrepo'
    yumrepo_core: 'puppetlabs/yumrepo_core'
